/**
 * NeoCard Component - Widget Template
 * 
 * Acts as the widget template that handles:
 * - Pagination logic for condensed view
 * - Page indicator display
 * - Expand button
 * - Title rendering
 * 
 * Widgets define their pages and expanded view, and NeoCard handles all the
 * pagination, scrolling, and UI infrastructure.
 * 
 * Used by: All widget components (StockPriceCard, TotalBalanceCard, etc.)
 */
import React, { useState, useRef } from 'react';
import { View, Text, StyleSheet, ScrollView, Dimensions, NativeScrollEvent, NativeSyntheticEvent, useWindowDimensions } from 'react-native';
import Svg, { Defs, LinearGradient, Stop, Rect, Pattern, Circle } from 'react-native-svg';
import { colors } from '../../theme/colors';
import { typography } from '../../theme/typography';
import { NeoDotsButton } from './NeoDotsButton';
import { WidgetPageIndicator } from '../widgets/WidgetPageIndicator';

export const CARD_RADIUS = 6;

export type NeoCardProps = {
  title: string;                    // Title generated by widget from payload
  onExpand?: () => void;           // Callback when expand button is pressed
  expanded?: boolean;              // Whether widget is in expanded view
  condensedPages?: React.ReactElement[]; // Pages for condensed view (from widget)
  expandedView?: React.ReactElement;      // Content for expanded view (from widget)
};

export const NeoCard: React.FC<NeoCardProps> = ({ 
  title, 
  onExpand, 
  expanded = false,
  condensedPages = [],
  expandedView,
}) => {
  const [currentPage, setCurrentPage] = useState(0);
  const scrollViewRef = useRef<ScrollView>(null);
  const expandedScrollViewRef = useRef<ScrollView>(null);
  const [cardWidth, setCardWidth] = useState(() => Dimensions.get('window').width - 36);
  const [scrollViewHeight, setScrollViewHeight] = useState(0);
  const totalPages = condensedPages.length;
  
  // Generate unique IDs for SVG gradients to avoid conflicts
  const cardId = useRef(Math.random().toString(36).substring(2, 11)).current;

  // Helper to create gradient stops (reused across multiple gradients)
  const gradientStops = [
    <Stop key="0" offset="0%" stopColor={colors.pastelBlue} stopOpacity="0.55" />,
    <Stop key="1" offset="50%" stopColor={colors.pastelMint} stopOpacity="0.45" />,
    <Stop key="2" offset="100%" stopColor={colors.pastelBlush} stopOpacity="0.55" />,
  ];

  // Handle scroll for pagination
  const maybeUpdateWidth = (nextWidth: number) => {
    if (!nextWidth) return;
    setCardWidth(prev => (Math.abs(prev - nextWidth) < 0.5 ? prev : nextWidth));
  };

  const handleScroll = (event: NativeSyntheticEvent<NativeScrollEvent>) => {
    const { contentOffset, layoutMeasurement } = event.nativeEvent;
    if (layoutMeasurement?.width) {
      maybeUpdateWidth(layoutMeasurement.width);
    }
    const width = layoutMeasurement?.width || cardWidth || 1;
    const page = Math.round(contentOffset.x / width);
    setCurrentPage(page);
  };

  return (
    <View style={[styles.cardWrapper, expanded && styles.cardWrapperExpanded]}>
      <View style={[styles.card, expanded && styles.cardExpanded]}>
        {/* Subtle Background Pattern - Only show in condensed view */}
        {!expanded && (
          <View style={styles.patternOverlay} pointerEvents="none">
            <Svg width="100%" height="100%" style={StyleSheet.absoluteFill}>
              <Defs>
                <Pattern id={`dotPattern-${cardId}`} x="0" y="0" width="8" height="8" patternUnits="userSpaceOnUse">
                  <Circle cx="4" cy="4" r="0.5" fill={colors.ink} opacity="0.03" />
                </Pattern>
              </Defs>
              <Rect width="100%" height="100%" fill={`url(#dotPattern-${cardId})`} />
            </Svg>
          </View>
        )}

        {/* Header Stripe - Only show in condensed view */}
        {!expanded && (
          <View style={styles.headerStripe} pointerEvents="none">
            <View style={styles.greyLine} />
          </View>
        )}

        {/* Inner glow overlays for depth - Only show in condensed view */}
        {!expanded && (
          <View style={styles.innerGlow} pointerEvents="none">
            <Svg width="100%" height="100%" style={StyleSheet.absoluteFill}>
              <Defs>
                <LinearGradient id={`innerGlowTop-${cardId}`} x1="0%" y1="0%" x2="0%" y2="100%">
                  <Stop offset="0%" stopColor={colors.pastelLilac} stopOpacity="0.08" />
                  <Stop offset="100%" stopColor="transparent" stopOpacity="0" />
                </LinearGradient>
                <LinearGradient id={`innerGlowBottom-${cardId}`} x1="0%" y1="100%" x2="0%" y2="0%">
                  <Stop offset="0%" stopColor={colors.pastelBlush} stopOpacity="0.06" />
                  <Stop offset="100%" stopColor="transparent" stopOpacity="0" />
                </LinearGradient>
                <LinearGradient id={`innerGlowLeft-${cardId}`} x1="0%" y1="0%" x2="100%" y2="0%">
                  <Stop offset="0%" stopColor={colors.pastelBlue} stopOpacity="0.05" />
                  <Stop offset="100%" stopColor="transparent" stopOpacity="0" />
                </LinearGradient>
                <LinearGradient id={`innerGlowRight-${cardId}`} x1="100%" y1="0%" x2="0%" y2="0%">
                  <Stop offset="0%" stopColor={colors.pastelMint} stopOpacity="0.05" />
                  <Stop offset="100%" stopColor="transparent" stopOpacity="0" />
                </LinearGradient>
              </Defs>
              <Rect width="100%" height="30%" fill={`url(#innerGlowTop-${cardId})`} />
              <Rect y="70%" width="100%" height="30%" fill={`url(#innerGlowBottom-${cardId})`} />
              <Rect width="30%" height="100%" fill={`url(#innerGlowLeft-${cardId})`} />
              <Rect x="70%" width="30%" height="100%" fill={`url(#innerGlowRight-${cardId})`} />
            </Svg>
          </View>
        )}

        {/* Content Layer - Above all decorative elements */}
        <View style={styles.contentLayer}>
          {/* Title - Only for condensed view */}
          {!expanded && (
            <View style={styles.titleContainer}>
              <Text style={styles.title}>{title}</Text>
              {onExpand && (
                <NeoDotsButton onPress={onExpand} expanded={expanded} style={styles.expand} testID="expand-btn" />
              )}
            </View>
          )}

          {expanded ? (
            // EXPANDED VIEW: ScrollView wraps entire content for scrolling
            <ScrollView
              ref={expandedScrollViewRef}
              style={styles.expandedScrollView}
              contentContainerStyle={styles.expandedScrollContent}
              showsVerticalScrollIndicator={true}
              stickyHeaderIndices={[0]}
              onLayout={(event) => {
                const { height } = event.nativeEvent.layout;
                setScrollViewHeight(height);
              }}
            >
              {/* Sticky Title Header - Matches condensed view exactly */}
              <View style={styles.titleContainerSticky}>
                <View style={styles.titleRow}>
                  <Text style={styles.title}>{title}</Text>
                  {onExpand && (
                    <NeoDotsButton onPress={onExpand} expanded={expanded} style={styles.expand} testID="expand-btn" />
                  )}
                </View>
                {/* Grey line separating title from content */}
                <View style={styles.stickyHeaderStripe} pointerEvents="none">
                  <View style={styles.greyLine} />
                </View>
              </View>
              {/* Scrollable content below sticky title */}
              <View style={[styles.expandedContent, scrollViewHeight > 0 && { minHeight: Math.max(scrollViewHeight - 80, 400) }]}>
                {expandedView}
              </View>
            </ScrollView>
          ) : (
            // CONDENSED VIEW: Handle pagination
            <>
              {totalPages > 0 ? (
                <ScrollView
                  ref={scrollViewRef}
                  horizontal
                  pagingEnabled
                  showsHorizontalScrollIndicator={false}
                  onScroll={handleScroll}
                  scrollEventThrottle={16}
                  style={styles.scrollView}
                  onLayout={(event) => {
                    maybeUpdateWidth(event.nativeEvent.layout.width);
                  }}
                >
                  {condensedPages.map((page, index) => (
                    <View key={index} style={[styles.page, { width: cardWidth }]}>
                      {page}
                    </View>
                  ))}
                </ScrollView>
              ) : null}
              {totalPages > 1 && (
                <WidgetPageIndicator currentPage={currentPage} totalPages={totalPages} />
              )}
            </>
          )}
        </View>
      </View>
    </View>
  );
};

const styles = StyleSheet.create({
  cardWrapper: {
    marginHorizontal: 12,
    marginVertical: 8,
    shadowColor: colors.ink,
    shadowOpacity: 0.26,
    shadowRadius: 3,
    shadowOffset: { width: 2, height: 6 },
    elevation: 12,
    borderRadius: CARD_RADIUS + 2,
    backgroundColor: 'transparent',
  },
  cardWrapperExpanded: {
    marginHorizontal: 0,
    marginVertical: 0,
    shadowOpacity: 0,
    shadowRadius: 0,
    shadowOffset: { width: 0, height: 0 },
    elevation: 0,
    borderRadius: 0,
    flex: 1,
  },
  card: {
    backgroundColor: colors.cardBg,
    borderWidth: 1,
    borderColor: '#E0E0E0',
    borderRadius: CARD_RADIUS,
    paddingTop: 14,
    paddingBottom: 18,
    paddingHorizontal: 24,
    overflow: 'hidden',
  },
  cardExpanded: {
    borderRadius: 0,
    borderWidth: 0,
    borderColor: 'transparent',
    flex: 1,
    paddingTop: 0,
    paddingBottom: 0,
    paddingHorizontal: 0,
    backgroundColor: 'transparent',
    overflow: 'visible',
  },
  patternOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 0,
  },
  headerStripe: {
    position: 'absolute',
    top: 46, // Position below title area - equal spacing from title
    left: 0,
    right: 0,
    height: 1,
    zIndex: 1,
  },
  innerGlow: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 0,
    pointerEvents: 'none',
  },
  contentLayer: {
    position: 'relative',
    zIndex: 2,
    flex: 1,
  },
  titleContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  titleContainerSticky: {
    backgroundColor: colors.cardBg, // Solid background for sticky header
    zIndex: 10,
  },
  titleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
    paddingTop: 14,
    paddingHorizontal: 20, // Match screen edge padding
  },
  stickyHeaderStripe: {
    height: 1,
    width: '100%',
    position: 'relative',
  },
  greyLine: {
    width: '100%',
    height: 1,
    backgroundColor: '#E0E0E0',
  },
  title: { 
    ...typography.heading,
    fontSize: 17,
    color: colors.ink,
    letterSpacing: -0.4,
    flex: 1,
  },
  expand: { 
    marginLeft: 12,
  },
  scrollView: {
    marginHorizontal: -24, // Offset card padding for full-width scrolling
  },
  page: {
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
    paddingHorizontal: 24,
  },
  expandedScrollView: {
    flex: 1,
  },
  expandedScrollContent: {
    flexGrow: 1,
    minHeight: '100%',
  },
  expandedContent: {
    paddingHorizontal: 20, // Consistent padding from screen edges
    backgroundColor: colors.cardBg,
    flexGrow: 1,
    minHeight: 400,
  },
});

