/**
 * NeoCard Component - Widget Template
 * 
 * Acts as the widget template that handles:
 * - Pagination logic for condensed view
 * - Page indicator display
 * - Expand button
 * - Title rendering
 * 
 * Widgets define their pages and expanded view, and NeoCard handles all the
 * pagination, scrolling, and UI infrastructure.
 * 
 * Used by: All widget components (StockPriceCard, TotalBalanceCard, etc.)
 */
import React, { useState, useRef } from 'react';
import { View, Text, StyleSheet, ScrollView, Dimensions, NativeScrollEvent, NativeSyntheticEvent } from 'react-native';
import { colors } from '../../theme/colors';
import { typography } from '../../theme/typography';
import { NeoDotsButton } from './NeoDotsButton';
import { WidgetPageIndicator } from '../widgets/WidgetPageIndicator';

export const CARD_RADIUS = 10;

export type NeoCardProps = {
  title: string;                    // Title generated by widget from payload
  onExpand?: () => void;           // Callback when expand button is pressed
  expanded?: boolean;              // Whether widget is in expanded view
  condensedPages?: React.ReactElement[]; // Pages for condensed view (from widget)
  expandedView?: React.ReactElement;      // Content for expanded view (from widget)
};

export const NeoCard: React.FC<NeoCardProps> = ({ 
  title, 
  onExpand, 
  expanded = false,
  condensedPages = [],
  expandedView,
}) => {
  const [currentPage, setCurrentPage] = useState(0);
  const scrollViewRef = useRef<ScrollView>(null);
  const [cardWidth, setCardWidth] = useState(() => Dimensions.get('window').width - 36);
  const totalPages = condensedPages.length;

  // Handle scroll for pagination
  const maybeUpdateWidth = (nextWidth: number) => {
    if (!nextWidth) return;
    setCardWidth(prev => (Math.abs(prev - nextWidth) < 0.5 ? prev : nextWidth));
  };

  const handleScroll = (event: NativeSyntheticEvent<NativeScrollEvent>) => {
    const { contentOffset, layoutMeasurement } = event.nativeEvent;
    if (layoutMeasurement?.width) {
      maybeUpdateWidth(layoutMeasurement.width);
    }
    const width = layoutMeasurement?.width || cardWidth || 1;
    const page = Math.round(contentOffset.x / width);
    setCurrentPage(page);
  };

  return (
    <View style={styles.card}>
      {onExpand && (
        <NeoDotsButton onPress={onExpand} style={styles.expand} testID="expand-btn" />
      )}
      <View style={{ marginBottom: 8 }}>
        <Text style={styles.title}>{title}</Text>
      </View>
      
      {expanded ? (
        // EXPANDED VIEW: Render expanded content
        <View style={styles.expandedContent}>
          {expandedView}
        </View>
      ) : (
        // CONDENSED VIEW: Handle pagination
        <>
          {totalPages > 0 ? (
            <ScrollView
              ref={scrollViewRef}
              horizontal
              pagingEnabled
              showsHorizontalScrollIndicator={false}
              onScroll={handleScroll}
              scrollEventThrottle={16}
              style={styles.scrollView}
              onLayout={(event) => {
                maybeUpdateWidth(event.nativeEvent.layout.width);
              }}
            >
              {condensedPages.map((page, index) => (
                <View key={index} style={[styles.page, { width: cardWidth }]}>
                  {page}
                </View>
              ))}
            </ScrollView>
          ) : null}
          {totalPages > 1 && (
            <WidgetPageIndicator currentPage={currentPage} totalPages={totalPages} />
          )}
        </>
      )}
    </View>
  );
};

const styles = StyleSheet.create({
  card: {
    backgroundColor: colors.cardBg,
    borderWidth: 4,
    borderColor: colors.ink,
    borderRadius: CARD_RADIUS,
    padding: 14,
    marginHorizontal: 18,
    marginVertical: 9,
    shadowColor: colors.shadow,
    shadowOpacity: 0.3,
    shadowRadius: 0,
    shadowOffset: { width: 6, height: 6 },
  },
  title: { 
    ...typography.heading,
    fontSize: 16,
    color: colors.ink 
  },
  expand: { 
    position: 'absolute', 
    top: 10, 
    right: 10, 
    zIndex: 2 
  },
  scrollView: {
    marginHorizontal: -14, // Offset card padding for full-width scrolling
  },
  page: {
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
  },
  expandedContent: {
    // No special styling needed - widget handles its own layout
  },
});

